- name: Rsyslogd config and ZFS filesystem for Log Server role
  template:
    src: logserver.conf.j2
    dest: '{{ rsyslog_conf_logserver }}'
    mode: 0644
    owner: root
    group: root
    backup: no
  notify: rsyslog.service-restart

- name: Remove Hypervisor-specific config
  file:
    path: '{{ rsyslog_conf_hypervisor }}'
    state: absent

- name: Create ZFS filesystem for logserver storage
  zfs:
    name: '{{ logserver_zfs_fs }}'
    state: present
