---

- copy: src=isc-dhcp-relay.tmpl dest=/etc/confd/templates/isc-dhcp-relay.tmpl owner=root mode=0644
  notify:
  - confd-restart

- template: src=isc-dhcp-relay.toml.j2 dest=/etc/confd/conf.d/isc-dhcp-relay.toml owner=root mode=0644
  notify:
  - confd-restart

- service: name=confd state=started enabled=yes

- template: src=dhcrelay.service.j2 dest=/etc/systemd/system/dhcrelay.service owner=root mode=0644
  notify:
  - systemd-reload
  - dhcrelay-restart

- service: name=dhcrelay.service state=started enabled=yes

- template: src=dhcrelay-announce.service.j2 dest=/etc/systemd/system/dhcrelay-announce.service owner=root mode=0644
  notify:
  - systemd-reload
  - dhcrelay-announce-restart

- service: name=dhcrelay-announce.service state=started enabled=yes
