---

- template: src=tftpd.service.j2 dest=/etc/systemd/system/tftpd.service owner=root mode=0644
  notify:
  - systemd-reload
  - tftpd.service-restart

- service: name=tftpd.service state=started enabled=yes

- template: src=tftpd-announce.service.j2 dest=/etc/systemd/system/tftpd-announce.service owner=root mode=0644
  notify:
  - systemd-reload
  - tftpd-announce-restart

- service: name=tftpd-announce.service state=started enabled=yes
