---

- template: src=cdhcpd.service.j2 dest=/etc/systemd/system/cdhcpd.service owner=root mode=0644
  notify:
  - systemd-reload
  - cdhcpd-restart

- service: name=cdhcpd.service state=started enabled=yes
