---
- template: src=nfirewalld.service.j2 dest=/etc/systemd/system/nfirewalld.service owner=root mode=0644
  notify:
    - systemd-reload
    - nfirewalld-restart

- service: name=nfirewalld state=started enabled=yes
