---

- template: src=node-announce.service.j2 dest=/etc/systemd/system/node-announce.service owner=root mode=0744
  notify: systemd-reload
  notify: node-announce-restart

- service: name=node-announce.service state=started enabled=yes
