---
- copy: src=grootslang.service dest=/etc/systemd/system/grootslang.service owner=root mode=0644
  notify:
  - systemd-reload
  - grootslang-restart

- service: name=grootslang state=started enabled=yes

- template: src=grootslang-announce.service.j2 dest=/etc/systemd/system/grootslang-announce.service owner=root mode=0644
  notify:
  - systemd-reload
  - grootslang-announce-restart

- service: name=grootslang-announce state=started enabled=yes
