---
- stat: path=/etc/systemd/system/cplacerd.service
  register: cplacerd_service_stat

- service: name=cplacerd state=stopped enabled=no
  when: cplacerd_service_stat.stat.exists

- file: path=/etc/systemd/system/cplacerd.service state=absent
  notify:
  - systemd-reload
