---

- template: src=dobharchu.service.j2 dest=/etc/systemd/system/dobharchu.service owner=root mode=0644
  notify:
  - systemd-reload
  - dobharchu-restart

- service: name=dobharchu.service state=started enabled=yes
